### ISSUE TITLE
Loading existing Gist fails

### ISSUE THREAD

**Issue by zephyrict** [mstijak/tdo#10]
Hi, I love the site/app and I wanted to load an existing Gist created on another PC but it doesn't seem to work. Tried a few things but nothing seems to work. Probably overlooking something.

**Comment by mstijak** [comment]
That's strange. I just tried and it's working.

A long shot, but did you paste the full url or just id of the gist. It should be only id...

Do you see a request being made in Developer tools?

**Comment by zephyrict** [comment]
It is weird, I have tried it in different browsers, using only the ID, not the entire url. I'm sure it must be something with my PC or network. I'm not seeing any requests being made, which is also weird. I've disabled all extensions and everything but it doesn't help. I'll test some more and keep you updated.

**Comment by mstijak** [comment]
I'm going to close this issue. Feel free to re-open it if necessary.
