### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by pierre521** [mstijak/tdo#11]
Hi,
I have a little question with the use of tdo. I install tdo on my linux on local. Every time I want to use it I have to open the terminal and run yarn start ? Is it not possible to run everytime ?
Sorry for this question i'm a novice ..
Pierre

**Comment by mstijak** [comment]
You don't have to install and run it locally. You may access the hosted version directly from the browser:
https://mstijak.github.io/tdo/

I guess you can just bookmark it or pin tdo tab if you use Chrome.

Your tdo's are stored in localStorage or GitHub. It doesn't matter where the client app is hosted.

**Comment by pierre521** [comment]
But it's not private ? And if a clear the cache of my browser I lose my tasks, no ?

**Comment by mstijak** [comment]
If you want to preserve data you must use private gist storage. Private gists are tied to your GitHub account and can be accessed by someone else only if you share the url. 
In this case you'll share the information with the tdo app which will store it in your browser and use it only to communicate with GitHub. Only API tdo contacts is GitHub's API.

https://gist.github.com/

**Comment by pierre521** [comment]
Thank for your reply Mstijak I understand. 
And if I want to install on local or in my server I have to start each time I want to use it ?

**Comment by mstijak** [comment]
Please note that your data is stored either in a GitHub gist or browser's localStorage. 

App files may be hosted anywhere. That's just a shell.

**Comment by pierre521** [comment]
Ok thanks for your reply Mstijak and thanks for this beautiful tool !
