### ISSUE TITLE
Touch support

### ISSUE THREAD

**Issue by trst** [mstijak/tdo#14]
Using tdo on a phone is difficult and some actions are unusable (e.g. Double click on a section heading). Perhaps, enable long pressing or expose an alternative ui control for touch users?

**Comment by mstijak** [comment]
Yes, touch support is missing. For a start, I would like to add a pen icon for editing lists and hide the top bar under a hamburger menu.

**Comment by trst** [comment]
With an external keyboard on the iPad Pro, tdo is usable :) but I think those small affordances will make all the difference on touch only platforms.

Perhaps when in editing mode, a sort/drag icon to the side of each task would be useful to help rearrange tasks without a physical keyboard.

**Comment by mstijak** [comment]
I made the changes as described above. I like the menu. I'm not sure if pencil icons should be visible or not on desktops, so I'll leave them for now.

Drag & drop would be nice, but it'is not possible at the moment. The underlying front-end library (Cx) doesn't support it yet.
