### ISSUE TITLE
installation / operation on local server

### ISSUE THREAD

**Issue by nnako** [mstijak/tdo#17]
Hi,

I really like the easy to use frontend of this tool (e.g. with vim-like keyboard bindings) and its capabilities regarding general task management. So, I'd like to run the application on my local server (e.g. on a RaspberryPi). Unfortunately, I have not found any help on the following subjects:

- installation process without yarn
- application structure and restrictions

Eventually, I got something installed (which after many minutes of download and installation does not really look like having anything to do with "tdo"). I tried with

- git clone https://github.com/mstijak/todo.git ~/tdo
- cd ~/tdo
- npm install

But now, I wouldn't know, how or what to connect / configure in order to make the application accessible from a web browser within the connected LAN.

**Is there some more help on installation and application structure? Would it be possible to operate this application on a server hosted on a RaspberryPi, anyway?**

Please see the attached image in order to grasp the rough application in mind:

![tdo__structure_with_rpi](https://cloud.githubusercontent.com/assets/5845602/21591199/26b6ce84-d102-11e6-9acf-96029ed7ee7b.png)

Thanks in advance.

**Comment by mstijak** [comment]
Hi, it's really simple. You should run:
```
npm install
npm run build
```
After that just copy the contents of the `dist` folder to your webserver.

**Comment by nnako** [comment]
Thanks for your help so far. Unfortunately, building tdo on a RaspberryPi doesn't seem to work as expected. I previously successfully installed `node v6.9.2` and `npm v3.10.9` . Seem to be the same warnings / errors as with `node v5.x` which I tried before.

The `dist` folder contains just the `index.html` and two jpg pictures within a sub folder `assets`. The created `index.html`just contains the compilation log as displayed below. Please see the text below for some details.

Here are some warnings from the long build log after entering `npm install` within the module folder:

    g++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.4.0"' -I/home/pi/.node-gyp/6.9.2/include/node -I/home/pi/.node-gyp/6.9.2/src -I/home/pi/.node-gyp/6.9.2/deps/uv/include -I/home/pi/.node-gyp/6.9.2/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -std=gnu++0x -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/lexer.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/lexer.o ../src/libsass/src/lexer.cpp ../src/libsass/src/lexer.cpp: In function ‘bool Sass::Prelexer::is_nonascii(const char&)’:

    ../src/libsass/src/lexer.cpp:84:48: warning: comparison is always true due to limited range of data type [-Wtype-limits]
         (unsigned(chr) >= 128 && unsigned(chr) <= 15572911) ||
                                                ^
    ../src/libsass/src/lexer.cpp:85:24: warning: comparison is always false due to limited range of data type [-Wtype-limits]
         (unsigned(chr) >= 15630464 && unsigned(chr) <= 15712189) ||
                        ^
    ../src/libsass/src/lexer.cpp:85:53: warning: comparison is always true due to limited range of data type [-Wtype-limits]
         (unsigned(chr) >= 15630464 && unsigned(chr) <= 15712189) ||
                                                     ^
    ../src/libsass/src/lexer.cpp:86:24: warning: comparison is always false due to limited range of data type [-Wtype-limits]
         (unsigned(chr) >= 4036001920)
                        ^

And the end message:

    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

After running `npm run build` I get the followinf output:

    > tdo@1.0.0 build /home/pi/_tdo
    > webpack --config config/webpack.prod.js
    
    keywords if/then/else require v5 option
    Hash: ffa6f535e5d019dc2432
    Version: webpack 2.1.0-beta.28
    Time: 2475ms
                    Asset       Size  Chunks           Chunk Names
               index.html    3.01 kB  [emitted]
       assets/favicon.png  699 bytes  [emitted]
    assets/screenshot.png      31 kB  [emitted]
    
    ERROR in Entry module not found: Error: Can't resolve 'babel' in '/home/pi/_tdo'
    BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                     You need to specify 'babel-loader' instead of 'babel'.
    
    ERROR in   Error: Child compilation failed:
      Module not found: Error: Can't resolve 'babel' in '/home/pi/_tdo'
      BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                       You need to specify 'babel-loader' instead of 'babel'.:
      Error: Can't resolve 'babel' in '/home/pi/_tdo'
      BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                       You need to specify 'babel-loader' instead of 'babel'.
    
      - compiler.js:76
        [_tdo]/[html-webpack-plugin]/lib/compiler.js:76:16
    
      - Compiler.js:282 Compiler.<anonymous>
        [_tdo]/[webpack]/lib/Compiler.js:282:10
    
      - Compiler.js:479
        [_tdo]/[webpack]/lib/Compiler.js:479:13
    
      - Tapable.js:102 next
        [_tdo]/[tapable]/lib/Tapable.js:102:11
    
      - CachePlugin.js:61 Compiler.<anonymous>
        [_tdo]/[webpack]/lib/CachePlugin.js:61:4
    
      - Tapable.js:106 Compiler.applyPluginsAsyncSeries
         [_tdo]/[tapable]/lib/Tapable.js:106:13
     
      - Compiler.js:476
         [_tdo]/[webpack]/lib/Compiler.js:476:10
     
      - Tapable.js:95 Compilation.applyPluginsAsyncSeries
        [_tdo]/[tapable]/lib/Tapable.js:95:46
    
      - Compilation.js:628
        [_tdo]/[webpack]/lib/Compilation.js:628:18
    
      - Tapable.js:95 Compilation.applyPluginsAsyncSeries
        [_tdo]/[tapable]/lib/Tapable.js:95:46
    
      - Compilation.js:619
        [_tdo]/[webpack]/lib/Compilation.js:619:10
    
      - Tapable.js:102 next
        [_tdo]/[tapable]/lib/Tapable.js:102:11
    
      - UglifyJsPlugin.js:144 Compilation.<anonymous>
        [_tdo]/[webpack]/lib/optimize/UglifyJsPlugin.js:144:4
    
      - Tapable.js:106 Compilation.applyPluginsAsyncSeries
        [_tdo]/[tapable]/lib/Tapable.js:106:13
    
      - Compilation.js:614
        [_tdo]/[webpack]/lib/Compilation.js:614:9
    
      - Tapable.js:95 Compilation.applyPluginsAsyncSeries
        [_tdo]/[tapable]/lib/Tapable.js:95:46
    
      - Compilation.js:610
        [_tdo]/[webpack]/lib/Compilation.js:610:8
    
      - Tapable.js:95 Compilation.applyPluginsAsyncSeries
        [_tdo]/[tapable]/lib/Tapable.js:95:46
     
       - Compilation.js:556 Compilation.seal
         [_tdo]/[webpack]/lib/Compilation.js:556:7
     
       - Compiler.js:473
         [_tdo]/[webpack]/lib/Compiler.js:473:16
     
       - Tapable.js:189
         [_tdo]/[tapable]/lib/Tapable.js:189:11
     
       - Compilation.js:453 Compilation.<anonymous>
         [_tdo]/[webpack]/lib/Compilation.js:453:10
     
       - Compilation.js:424
         [_tdo]/[webpack]/lib/Compilation.js:424:12
     
       - Compilation.js:336
         [_tdo]/[webpack]/lib/Compilation.js:336:10
     

       - async.js:356
         [_tdo]/[webpack]/[async]/dist/async.js:356:16
     
       - async.js:936 iteratorCallback
         [_tdo]/[webpack]/[async]/dist/async.js:936:13
     
       - async.js:840
         [_tdo]/[webpack]/[async]/dist/async.js:840:16
     
        - Compilation.js:202 errorAndCallback
         [_tdo]/[webpack]/lib/Compilation.js:202:5
     
       - Compilation.js:229 errorOrWarningAndCallback
         [_tdo]/[webpack]/lib/Compilation.js:229:13
     
       - Compilation.js:233
         [_tdo]/[webpack]/lib/Compilation.js:233:12
    
    
    Child html-webpack-plugin for "index.html":
           [0] ./~/html-webpack-plugin/lib/loader.js!./app/index.html 1.29 kB {0} [built]
    
        ERROR in ./~/html-webpack-plugin/lib/loader.js!./app/index.html
        Module not found: Error: Can't resolve 'babel' in '/home/pi/_tdo'
        BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                         You need to specify 'babel-loader' instead of 'babel'.
         @ ./~/html-webpack-plugin/lib/loader.js!./app/index.html 1:8-53
    
    npm ERR! Linux 4.4.26-v7+
    npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
    npm ERR! node v6.9.2
    npm ERR! npm  v3.10.9
    npm ERR! code ELIFECYCLE
    npm ERR! tdo@1.0.0 build: `webpack --config config/webpack.prod.js`
    npm ERR! Exit status 2
    npm ERR!
    npm ERR! Failed at the tdo@1.0.0 build script 'webpack --config config/webpack.prod.js'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the tdo package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     webpack --config config/webpack.prod.js
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs tdo
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls tdo
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/pi/_tdo/npm-debug.log

And here the `npm-debug.log` as picture (text upload is somehow not possible on GitHub):
![tdo__installation-log](https://cloud.githubusercontent.com/assets/5845602/21592954/7129a3f0-d112-11e6-992d-ba8783906527.png)

**Any hints?**

**Comment by mstijak** [comment]
I made some changes required by the latest version of `webpack`. It should work now.

**Comment by nnako** [comment]
Great!!! It works nicely, now :-)

Just for your information, here's the output of the command`npm run build` (just two size limits and one performance recommendation). In case a feedback is helpful for optimization:

    > tdo@1.0.0 build /home/pi/_tdo
    > webpack --config config/webpack.prod.js

    keywords if/then/else require v5 option
    [BABEL] Note: The code generator has deoptimised the styling of "/home/pi/_tdo/node_modules/lodash/lodash.js" as it exceeds the max of "500KB".
    Hash: 431d4aaf02f0c7f08c40
    Version: webpack 2.1.0-beta.28
    Time: 230467ms
                    Asset       Size  Chunks           Chunk Names
                   app.js     290 kB  0[emitted]  [big]app
                  app.css    89.3 kB  0[emitted]  app
               index.html    1.05 kB  [emitted]
       assets/favicon.png  699 bytes  [emitted]
    assets/screenshot.png      31 kB  [emitted]
      [11] ./app/data/actions/index.js 1.27 kB {0} [built]
      [32] ./app/data/services/Gists.js 2.85 kB {0} [built]
      [43] ./app/data/actions/board.js 911 bytes {0} [built]
      [44] ./app/data/reducers/dummyReducer.js 220 bytes {0} [built]
      [45] ./app/data/services/GHAuth.js 513 bytes {0} [built]
      [71] ./app/data/middleware/index.js 151 bytes {0} [built]
      [72] ./app/data/reducers/index.js 243 bytes {0} [built]
      [73] ./app/routes/index.js 10 kB {0} [built]
      [75] ./app/index.scss 41 bytes {0} [built]
      [77] ./app/data/middleware/boardNavigation.js 803 bytes {0} [built]
      [78] ./app/data/middleware/persist.js 923 bytes {0} [built]
      [79] ./app/data/reducers/tdo/boards/index.js 1.07 kB {0} [built]
      [80] ./app/data/reducers/tdo/cleanup.js 2.73 kB {0} [built]
      [81] ./app/data/reducers/tdo/getDefaultData.js 401 bytes {0} [built]
      [82] ./app/data/reducers/tdo/index.js 1.3 kB {0} [built]
      [83] ./app/data/reducers/tdo/lists/index.js 227 bytes {0} [built]
      [84] ./app/data/reducers/tdo/migrate.js 2.63 kB {0} [built]
      [85] ./app/data/reducers/tdo/tasks/index.js 227 bytes {0} [built]
      [86] ./app/data/reducers/tdo/tutorial.js 3.23 kB {0} [built]
      [87] ./app/routes/Controller.js 2.1 kB {0} [built]
      [88] ./app/routes/default/BoardEditor.js 4.76 kB {0} [built]
      [89] ./app/routes/default/Controller.js 14.6 kB {0} [built]
      [90] ./app/routes/default/ListEditor.js 5.41 kB {0} [built]
      [91] ./app/routes/default/Task.js 9.23 kB {0} [built]
      [92] ./app/routes/default/index.js 10.7 kB {0} [built]
      [93] ./app/routes/default/styling.js 1.17 kB {0} [built]
      [94] ./app/routes/help/index.js 2.06 kB {0} [built]
      [95] ./app/routes/settings/Controller.js 3.47 kB {0} [built]
      [96] ./app/routes/settings/index.js 10.9 kB {0} [built]
     [168] ./app/index.js 4.04 kB {0} [built]
        + 139 hidden modules

    WARNING in asset size limit: The following asset(s) exceed the recommended size limit (250 kB).
    This can impact web performance.
    Assets:
      app.js (290 kB)

    WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (250 kB). This can impact web performance.
    Entrypoints:
      app (379 kB)
          app.js
          app.css


    WARNING in webpack performance recommendations:
    You can limit the size of your bundles by using System.import() or require.ensure to lazy load some parts of your application.
    For more info visit https://webpack.js.org/guides/code-splitting/
    Child html-webpack-plugin for "index.html":
           [4] ./~/html-webpack-plugin/lib/loader.js!./app/index.html 1.29 kB {0} [built]
            + 4 hidden modules
    Child extract-text-webpack-plugin:
           [1] ./~/css-loader!./~/sass-loader!./app/index.scss 93 kB {0} [built]
            + 1 hidden modules
