### ISSUE TITLE
Deleted Boards still appear in dropdown while editing Lists

### ISSUE THREAD

**Issue by jordan-rich** [mstijak/tdo#27]
On MacOS High Sierra Safari 12 Deleted boards still appear in the dropdown while editing lists. It can be little confusing. As a workaround I'll just be sure to rename it to something else before deleting. 
![image 2018-10-23 at 9 02 47 am](https://user-images.githubusercontent.com/3683251/47378604-a383e980-d6c6-11e8-8552-400dd741b14d.png)

**Comment by jacekk** [comment]
I can work on that ... in the evening. @mstijak 

@builtbyjordan Thx for reporting.

**Comment by jacekk** [comment]
@mstijak I can see you are working on it in a different repo: https://github.com/codaxy/tdo/commits/master . Is this repo obsolete?

**Comment by mstijak** [comment]
@jacekk Thanks, that would be great. I'm working on a new version of tdo which will be based on Firebase. Firebase should enable some cool new features like data sharing between users and devices, offline mode, google sign in, etc. This repo will become obsolete once the new repo stabilize. That might take some time. There is a lot of work left and I'm very busy with other things at the moment.

**Comment by jordan-rich** [comment]
Good to know there something in the works! @jacekk Thanks for jumping in!

**Comment by jacekk** [comment]
@builtbyjordan Fixed & released. Can you verify? And close this very ticket?

**Comment by jordan-rich** [comment]
@jacekk Yes. I'll get to that this afternoon.

**Comment by jordan-rich** [comment]
Confirming that deleted boards do not show up in the dropdown anyone. Great job!
