### ISSUE TITLE
Alexa Integration?

### ISSUE THREAD

**Issue by harrisonhjones** [mstijak/tdo#4]
Saw tdo on HN today. Pretty neat. Thought about [Alexa integration](https://developer.amazon.com/alexa-skills-kit/shopping-and-to-do-lists)? 

I'd be happy to write it (and keep it open-source!). The API for the integration isn't public yet so I'm not sure exactly what I need but I think we can use the gist-saving feature to do task retrieval however we also need to be able to update Amazon when a task has changed. Since GitHub [doesn't support Gist webhooks](https://developer.github.com/v3/activity/events/types/#gistevent) perhaps we can add a new custom field in the settings for an update webhook URL? 

Thoughts? I imagine we'd need to refine the integration requirements as we get more information but if you are interested I'll apply to be considered for the private beta.

**Comment by mstijak** [comment]
That sounds really interesting, although I'm not sure if I completely understand how would that work. Can you please explain a little bit. What kind of application is needed?

Some users asked about sync across multiple devices. To truly support that we would require some kind of a backend API and a proper domain name. That would enable cool things like real-time updates, proper sign-on with GitHub or Google (Drive), and to me that is the logical next step. I guess you could hook into that to send tasks from Alexa.

**Comment by harrisonhjones** [comment]
So the rub here is that the Alexa ToDo API is in private beta so I don't really know what is needed for certain however, unlike their APIs so far the ToDo API is bi-directional: when a task is updated on tdo a call needs to be made to Amazon to let Alexa know the list has changed so the Alexa cache can be updated. When a task is updated via Alexa a call is made to tdo to update the list. 

Since tdo isn't a real "service" yet we'd normally have a problem but given the gist integration we should be fine as long as we can add webhook support on the tdo side. Here's what I think needs to be done to support Alexa:

tdo/@mstijak: Add support for webhooks. Whenever the gist is updated also trigger a webhook (if configured). Could probably just be an AJAX call to the webhook URL. Not sure what information we would need to send with the hook but we'll figure that out as we go.

Alexa Skill/@harrisonhjones: Stand up an Alexa Skill (probably a lambda function) which would:
1. receive the tdo webhooks, read a users tdo gist (or get the update in the webhook body), update Amazon via the beta Alexa Skill API.
2. write to the tdo gist for the current user when a user updates their list via Alexa
3. Allow the user to login (via GitHub) and select their tdo gist. Would use the GitHub OAuth flow to login. Not 100% how to do the tdo gist selection without a proper hosted site or a bit of OAuth hackery. Not worried but it would be a bit of challenge.

I hope that helps! Let me know.

**Comment by mstijak** [comment]
It seems that you figured everything out. I think it would be best if you fork tdo and do it. If everything works out nicely, we can merge back later.

**Comment by harrisonhjones** [comment]
Sounds great. Will do. Closing this for now. Might ping you if I have any sytle-related questions.
